version: 0.2
phases:
  install:
    commands:
      - echo installing dependencies...
      - go mod download
  pre_build:
    commands:
      - Running unit tests...
      - cd tests
      - make test
